language: node_js
node_js:
  - "7"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project dreamblitz-83926 --token $FIREBASE_TOKEN
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - 8
branches:
  only:
    - master
    - '/^greenkeeper/.*$/'
